-- Phase 0: make the command counters live, and stop losing long commands.
--
-- cowrie_unique_commands.total_events / unique_ips were written by nothing.
-- The ingest endpoint only ever set command/first_seen/last_seen, migration
-- 006's trigger deliberately skipped commands, and no cron or timer touched
-- them. They were a one-off backfill, frozen since. Measured 2026-09-13:
--
--   total_events   'uname -a' stored 2,634 vs 2,882 actual   (~9% low)
--   unique_ips     sum 42,919 vs 2,948,377 actual distinct   (69x low)
--   155 of 3,833 rows had NULL total_events entirely
--
-- Anything ranked on those numbers was wrong; anything ranked on unique_ips
-- or a hits-per-IP ratio was wrong by two orders of magnitude.
--
-- Separately, the table's primary key was `command` (text). A btree index
-- entry cannot exceed ~2704 bytes, so the longest commands could never be
-- stored: of 45 distinct commands over 2000 bytes in cowrie_events, 44 were
-- absent from this table. 33 of those are /dev/tcp loader lines and 34 carry
-- base64 config blobs — precisely the payloads worth extracting. The PK moves
-- to a surrogate id with uniqueness on sha256(command), which has no length
-- limit, and the application-side 2000-byte cap can then be removed.

-- ---------------------------------------------------------------------------
-- 1. Re-key cowrie_unique_commands
-- ---------------------------------------------------------------------------

ALTER TABLE cowrie_unique_commands
  ADD COLUMN IF NOT EXISTS id bigint GENERATED BY DEFAULT AS IDENTITY,
  ADD COLUMN IF NOT EXISTS command_sha256 bytea;

-- sha256(convert_to(...)) is only STABLE, not IMMUTABLE — it depends on the
-- database encoding — so Postgres rejects it as a generated column. Migration
-- 008 hit the same wall on cowrie_unique_creds.password_sha256 and solved it
-- with a BEFORE trigger; same pattern here.
CREATE OR REPLACE FUNCTION set_command_sha256() RETURNS trigger AS $$
BEGIN
  NEW.command_sha256 := sha256(convert_to(NEW.command, 'UTF8'));
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_set_command_sha256 ON cowrie_unique_commands;
CREATE TRIGGER trg_set_command_sha256
  BEFORE INSERT OR UPDATE OF command ON cowrie_unique_commands
  FOR EACH ROW EXECUTE FUNCTION set_command_sha256();

UPDATE cowrie_unique_commands
   SET command_sha256 = sha256(convert_to(command, 'UTF8'))
 WHERE command_sha256 IS NULL;

ALTER TABLE cowrie_unique_commands ALTER COLUMN command_sha256 SET NOT NULL;

CREATE UNIQUE INDEX CONCURRENTLY IF NOT EXISTS uq_cowrie_unique_commands_sha256
  ON cowrie_unique_commands (command_sha256);

-- Swap the primary key. Dropping the text PK is what lifts the 2704-byte
-- ceiling; the sha256 unique index above is the replacement conflict target.
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_constraint
              WHERE conrelid = 'cowrie_unique_commands'::regclass
                AND contype = 'p' AND conname = 'cowrie_unique_commands_pkey') THEN
    ALTER TABLE cowrie_unique_commands DROP CONSTRAINT cowrie_unique_commands_pkey;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint
                  WHERE conrelid = 'cowrie_unique_commands'::regclass
                    AND contype = 'p') THEN
    ALTER TABLE cowrie_unique_commands ADD PRIMARY KEY (id);
  END IF;
END $$;

-- ---------------------------------------------------------------------------
-- 2. Companion pair table for unique_ips
-- ---------------------------------------------------------------------------
-- COUNT(DISTINCT src_ip) cannot be kept as a running counter, so the trigger
-- bumps unique_ips only when a (command, ip) pair is seen for the first time —
-- the same device as cowrie_asn_ips / cowrie_cred_ips. Keyed on the hash, not
-- the command text, for the same length reason as above.
--
-- Measured cardinality: 2,948,377 distinct pairs at the time of writing,
-- ~340 MB at the 103 bytes/row that cowrie_cred_ips actually costs.

CREATE TABLE IF NOT EXISTS cowrie_command_ips (
  command_sha256 bytea NOT NULL,
  src_ip         inet  NOT NULL,
  PRIMARY KEY (command_sha256, src_ip)
);

-- ---------------------------------------------------------------------------
-- 3. Backfill boundary marker
-- ---------------------------------------------------------------------------
-- The cutoff is an id, not a timestamp, because the forwarder's dead-letter
-- replay re-posts events whose `timestamp` is hours or days old. A timestamp
-- cutoff would hand those rows to both the trigger and the backfill and count
-- them twice. Ids are assigned by a sequence at insert time, so a replayed
-- event always lands above the cutoff regardless of when it claims to have
-- happened.
--
-- Fail-closed: while no marker row exists the trigger counts nothing. The
-- window between the function being replaced and the marker being written is
-- therefore covered by the backfill rather than being double-counted, and the
-- marker is written under a lock so no insert can straddle the boundary.

CREATE TABLE IF NOT EXISTS cowrie_backfill_marker (
  name       text PRIMARY KEY,
  cutoff_id  bigint NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  notes      text
);

-- ---------------------------------------------------------------------------
-- 4. Arm the boundary and extend the trigger, atomically
-- ---------------------------------------------------------------------------
-- These two have to happen together or the boundary leaks.
--
-- Capture-then-install as separate statements loses any row inserted between
-- them: the old function ignores commands, so the trigger never counts it, and
-- its id is above the cutoff, so the backfill never counts it either. Nothing
-- errors — the row is just silently absent, which is the failure mode this
-- whole migration exists to fix.
--
-- Install-then-capture is safe but double-counts instead, unless the trigger
-- fails closed on a missing marker (it does, above) — in which case the gap
-- rows fall to the backfill, which is correct but leaves the exact boundary
-- dependent on transaction visibility rather than on anything provable.
--
-- One transaction holding SHARE ROW EXCLUSIVE settles it. That mode blocks
-- concurrent INSERT and waits for in-flight ones to commit, so max(id) is
-- exact at the instant the new function goes live. Anything the lock held up
-- resumes afterwards, sees the marker, and carries an id above the cutoff, so
-- the trigger owns it. No row can straddle the boundary in either direction.
--
-- The lock is metadata-level and held for the duration of two small
-- statements — milliseconds — not for any scan of the 6.5 GB table. It does
-- briefly pause ingestion; the forwarder retries, as it is built to.

BEGIN;

LOCK TABLE cowrie_events IN SHARE ROW EXCLUSIVE MODE;

-- DO NOTHING, not DO UPDATE: replaying this migration (FORCE=1, or disaster
-- recovery) must not move a boundary the backfill has already been run against.
INSERT INTO cowrie_backfill_marker (name, cutoff_id, notes)
SELECT 'command_counters',
       COALESCE(max(id), 0),
       'Phase 0. Trigger counts id > cutoff; backfill owns id <= cutoff.'
  FROM cowrie_events
ON CONFLICT (name) DO NOTHING;

-- Everything above the commands block is migration 006 verbatim. Re-declared
-- in full because CREATE OR REPLACE FUNCTION has no partial form.

CREATE OR REPLACE FUNCTION sync_cowrie_event_aggs() RETURNS trigger AS $$
DECLARE
  new_ip boolean;
  cmd_hash bytea;
  cutoff bigint;
BEGIN
  IF NEW.asn IS NOT NULL THEN
    INSERT INTO cowrie_asn_ips (asn, src_ip)
    VALUES (NEW.asn, NEW.src_ip)
    ON CONFLICT DO NOTHING;
    new_ip := FOUND;

    INSERT INTO cowrie_asn_agg (asn, org, total, unique_ips)
    VALUES (NEW.asn, NEW.org, 1, CASE WHEN new_ip THEN 1 ELSE 0 END)
    ON CONFLICT (asn) DO UPDATE SET
      total      = cowrie_asn_agg.total + 1,
      unique_ips = cowrie_asn_agg.unique_ips + EXCLUDED.unique_ips,
      org        = COALESCE(cowrie_asn_agg.org, EXCLUDED.org);
  END IF;

  IF NEW.country_iso IS NOT NULL AND NEW.country_iso <> '' THEN
    INSERT INTO cowrie_country_ips (country_iso, src_ip)
    VALUES (NEW.country_iso, NEW.src_ip)
    ON CONFLICT DO NOTHING;
    new_ip := FOUND;

    INSERT INTO cowrie_country_agg (country_iso, total, unique_ips)
    VALUES (NEW.country_iso, 1, CASE WHEN new_ip THEN 1 ELSE 0 END)
    ON CONFLICT (country_iso) DO UPDATE SET
      total      = cowrie_country_agg.total + 1,
      unique_ips = cowrie_country_agg.unique_ips + EXCLUDED.unique_ips;
  END IF;

  IF NEW.username IS NOT NULL AND NEW.username <> ''
     AND NEW.password IS NOT NULL AND NEW.password <> ''
     AND octet_length(NEW.username) + octet_length(NEW.password) <= 1000 THEN
    INSERT INTO cowrie_cred_ips (username, password, src_ip)
    VALUES (NEW.username, NEW.password, NEW.src_ip)
    ON CONFLICT DO NOTHING;
    new_ip := FOUND;

    INSERT INTO cowrie_unique_creds (username, password, first_seen, last_seen, total_events, unique_ips)
    VALUES (NEW.username, NEW.password, NEW."timestamp", NEW."timestamp", 1, CASE WHEN new_ip THEN 1 ELSE 0 END)
    ON CONFLICT (username, password) DO UPDATE SET
      first_seen   = LEAST(cowrie_unique_creds.first_seen, EXCLUDED.first_seen),
      last_seen    = GREATEST(cowrie_unique_creds.last_seen, EXCLUDED.last_seen),
      total_events = COALESCE(cowrie_unique_creds.total_events, 0) + 1,
      unique_ips   = COALESCE(cowrie_unique_creds.unique_ips, 0) + EXCLUDED.unique_ips;
  END IF;

  -- ---- commands (new in 011) ----------------------------------------------
  IF NEW.command IS NOT NULL AND NEW.command <> '' THEN
    SELECT m.cutoff_id INTO cutoff
      FROM cowrie_backfill_marker m
     WHERE m.name = 'command_counters';

    -- No marker yet, or at/below the boundary: the backfill owns this row.
    IF cutoff IS NOT NULL AND NEW.id > cutoff THEN
      cmd_hash := sha256(convert_to(NEW.command, 'UTF8'));

      INSERT INTO cowrie_command_ips (command_sha256, src_ip)
      VALUES (cmd_hash, NEW.src_ip)
      ON CONFLICT DO NOTHING;
      new_ip := FOUND;

      -- No length guard: the hash is the key, so a 56 KB command indexes as
      -- cheaply as a 5-byte one. This is the loss that 011 exists to stop.
      INSERT INTO cowrie_unique_commands (command, command_sha256, first_seen, last_seen, total_events, unique_ips)
      VALUES (NEW.command, cmd_hash, NEW."timestamp", NEW."timestamp", 1, CASE WHEN new_ip THEN 1 ELSE 0 END)
      ON CONFLICT (command_sha256) DO UPDATE SET
        first_seen   = LEAST(cowrie_unique_commands.first_seen, EXCLUDED.first_seen),
        last_seen    = GREATEST(cowrie_unique_commands.last_seen, EXCLUDED.last_seen),
        total_events = COALESCE(cowrie_unique_commands.total_events, 0) + 1,
        unique_ips   = COALESCE(cowrie_unique_commands.unique_ips, 0) + EXCLUDED.unique_ips;
    END IF;
  END IF;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- The trigger itself is unchanged from 006 and is not re-created here: only
-- the function body moved, so there is nothing to drop or re-attach.

COMMIT;

-- After this point the trigger is live for every new event and the backfill
-- owns everything at or below the marker. Run db/backfill/011_command_counters.sh
-- next; until it does, total_events/unique_ips reflect only post-cutoff traffic
-- and must not be ranked on.
