-- Phase 4: structured indicators.
--
-- Every indicator this project can publish already exists inside
-- cowrie_unique_commands.command, as text. Answering "every C2 endpoint we
-- have seen" therefore means a regex over a text column, which cannot be
-- indexed, cannot record when an indicator was first or last seen, and
-- re-derives the same answer on every request. The /iocs endpoint currently
-- does exactly that for URLs, extracting them per request in JavaScript.
--
-- This stores them. Extraction stays in backend/lib/iocs.js — one definition
-- used by the ingest path and the backfill, for the same reason the
-- normalizer and the classifier are single-sourced: two copies of a rule
-- drift, and a drifted extractor publishes a wrong indicator feed without
-- erroring.
--
-- Measured over the 4,041 real commands: 188 carry at least one indicator,
-- giving 90 distinct URLs, 41 C2 endpoints, 49 config blobs, 3 Monero
-- wallets, 2 SSH keys and 2 hijacked resolvers.

-- ---------------------------------------------------------------------------
-- 1. Types
-- ---------------------------------------------------------------------------
-- An enum, matching cowrie_record_class. PostgreSQL 12+ takes
-- ALTER TYPE ... ADD VALUE IF NOT EXISTS outside a transaction block, and
-- apply-migrations.sh does not wrap migrations, so new indicator types stay
-- a one-line migration.

DO $$
BEGIN
  CREATE TYPE cowrie_ioc_type AS ENUM (
    'c2_endpoint', 'url', 'ssh_key', 'xmr_wallet',
    'config_blob', 'nameserver', 'dropped_credential'
  );
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

-- ---------------------------------------------------------------------------
-- 2. The table
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS cowrie_iocs (
  id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ioc_type          cowrie_ioc_type NOT NULL,
  value             text NOT NULL,
  value_sha256      bytea NOT NULL,
  -- Extractor output that is worth keeping but not worth a column each: the
  -- port behind a c2_endpoint, the algorithm and comment on an ssh_key, the
  -- size of a config_blob.
  meta              jsonb NOT NULL DEFAULT '{}'::jsonb,
  first_seen        timestamptz NOT NULL,
  last_seen         timestamptz NOT NULL,
  -- Distinct commands carrying this indicator, not total sightings. The
  -- loader names its C2 endpoint three times in one command; counting
  -- mentions would measure how many fallbacks the malware uses rather than
  -- how often we saw the server.
  occurrence_count  bigint NOT NULL DEFAULT 0,
  -- The first command it was found in, for "show me where this came from".
  source_command_id bigint
);

-- value_sha256 rather than value as the key, for the third time in this
-- schema and for the same reason each time. A btree entry stops at about 2704
-- bytes; migration 011 exists because this table's predecessor was keyed on
-- text and silently dropped 44 of the 45 commands over 2000 bytes, which were
-- the ones carrying C2 addresses. The largest indicator here is an 832-byte
-- config blob, comfortably inside the limit today — and "comfortably inside
-- the limit today" is precisely what was true before.
--
-- sha256(convert_to(...)) is STABLE, not IMMUTABLE, so it cannot be a
-- generated column. Same BEFORE trigger as migrations 008, 011 and 012.
CREATE OR REPLACE FUNCTION set_ioc_value_sha256() RETURNS trigger AS $$
BEGIN
  NEW.value_sha256 := sha256(convert_to(NEW.value, 'UTF8'));
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_set_ioc_value_sha256 ON cowrie_iocs;
CREATE TRIGGER trg_set_ioc_value_sha256
  BEFORE INSERT OR UPDATE OF value ON cowrie_iocs
  FOR EACH ROW EXECUTE FUNCTION set_ioc_value_sha256();

-- ---------------------------------------------------------------------------
-- 3. Indexes
-- ---------------------------------------------------------------------------
-- The conflict target for the upsert. Typed as well as hashed because the
-- same string can legitimately be two kinds of indicator.
CREATE UNIQUE INDEX CONCURRENTLY IF NOT EXISTS uq_cowrie_iocs_type_value
  ON cowrie_iocs (ioc_type, value_sha256);

-- What the endpoint asks: one type, inside a window, newest first.
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_cowrie_iocs_type_last_seen
  ON cowrie_iocs (ioc_type, last_seen DESC);

-- ---------------------------------------------------------------------------
-- 4. Which commands carry which indicator
-- ---------------------------------------------------------------------------
-- occurrence_count is "distinct commands carrying this indicator", and a
-- running counter cannot compute a COUNT(DISTINCT ...) on its own. The ingest
-- path therefore records the pair and increments only when the pair is new,
-- which is exactly the device migration 011 uses for unique_ips and migration
-- 006 for the per-ASN and per-country counts.
--
-- Without it, ingest would have to either skip the count (leaving every newly
-- seen indicator at zero until a backfill ran) or add one per sighting (which
-- counts the malware's retry loops rather than our observations).
--
-- Small by construction: one row per (indicator, command) pair, and only 188
-- of 4,041 commands carry an indicator at all.
CREATE TABLE IF NOT EXISTS cowrie_ioc_commands (
  ioc_id     bigint NOT NULL REFERENCES cowrie_iocs(id) ON DELETE CASCADE,
  command_id bigint NOT NULL,
  PRIMARY KEY (ioc_id, command_id)
);

-- ---------------------------------------------------------------------------
-- 5. Staging table for the backfill
-- ---------------------------------------------------------------------------
CREATE UNLOGGED TABLE IF NOT EXISTS cowrie_iocs_stage (
  ioc_type          text NOT NULL,
  value             text NOT NULL,
  meta              jsonb NOT NULL DEFAULT '{}'::jsonb,
  first_seen        timestamptz NOT NULL,
  last_seen         timestamptz NOT NULL,
  occurrence_count  bigint NOT NULL DEFAULT 1,
  source_command_id bigint
);

-- ---------------------------------------------------------------------------
-- 6. What this migration deliberately does NOT do
-- ---------------------------------------------------------------------------
-- It does not populate the table. Everything above is catalog-only and costs
-- no disk: creating a type, an empty table and two indexes on it.
--
-- Migration 013's first version classified 1.6M rows inline, filled the
-- volume and crashed PostgreSQL. The lesson generalises past that one case —
-- a migration should change the shape of the database, and a backfill should
-- change its contents, because only the backfill can be interrupted, resumed,
-- paced, and made to refuse to start when the disk is short.
--
-- Run db/backfill/014_iocs.sh after this. Until it does, the table is empty
-- and the /iocs endpoint keeps extracting per request, which is what it has
-- always done.
