-- Phase 3: the botnet peer map.
--
-- The honeypot captures the Panchan SSH worm being installed and started:
--
--   chmod +x ./.5187238377254817649/sshd;nohup ./.5187238377254817649/sshd \
--     177.10.201.11 170.150.255.26 ... 185.228.81.251 &
--
-- The addresses are the malware's argv, and they are peers rather than
-- victims: Panchan is peer-to-peer, and these are known-good nodes it
-- contacts to join the mesh on port 1919. The original plan for this phase
-- called the table peer_targets, on the reading that the worm was being
-- handed a victim list. It was not, and the distinction inverts the meaning
-- of every number here — a recurring address is a long-lived node, not a host
-- being attacked over and over.
--
-- Akamai documented the family in 2022 and Nozomi tracked it in 2024; the
-- exact sample this command deploys is in cowrie_files with 39 VirusTotal
-- detections. Both published enumerations are point-in-time crawls of the
-- live mesh, at 209 and 96 nodes. What this table holds is different in kind:
-- ten months of passive observation, collected without touching the botnet.
--
-- Measured over the corpus: 163 launch commands, 117 carrying a list and 46
-- passing none, 5,853 entries, 1,930 distinct peers. Lists are almost always
-- exactly 51 addresses.

-- ---------------------------------------------------------------------------
-- 1. The peers
-- ---------------------------------------------------------------------------
-- Geo columns mirror cowrie_events (country_iso, asn, org, city) so peer
-- geography and attacker geography can be compared without translating
-- between two shapes. Filled from the same MaxMind databases the API uses.

CREATE TABLE IF NOT EXISTS cowrie_botnet_peers (
  id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  peer_ip           inet NOT NULL UNIQUE,
  first_seen        timestamptz NOT NULL,
  last_seen         timestamptz NOT NULL,
  -- Distinct bootstrap lists this address has appeared in. The interesting
  -- signal in the corpus is that a handful of nodes recur across ten months
  -- while most appear once, so this is the column the analysis hangs on.
  list_count        bigint NOT NULL DEFAULT 0,
  country_iso       text,
  asn               integer,
  org               text,
  city              text,
  source_command_id bigint
);

-- "Which peers has this campaign been pointing at lately", and the recurrence
-- ranking, are the two questions asked of this table.
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_cowrie_botnet_peers_last_seen
  ON cowrie_botnet_peers (last_seen DESC);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_cowrie_botnet_peers_list_count
  ON cowrie_botnet_peers (list_count DESC);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_cowrie_botnet_peers_asn
  ON cowrie_botnet_peers (asn) WHERE asn IS NOT NULL;

-- ---------------------------------------------------------------------------
-- 2. Which list each peer came from
-- ---------------------------------------------------------------------------
-- list_count is a COUNT(DISTINCT ...), which a running counter cannot
-- maintain on its own, so the ingest path records the pair and increments
-- only when the pair is new. Same device as cowrie_command_ips (migration
-- 011) and cowrie_ioc_commands (migration 014).
--
-- It also answers a question the count alone cannot: which lists a given peer
-- appeared in, and therefore whether two peers travel together.

CREATE TABLE IF NOT EXISTS cowrie_peer_commands (
  peer_id    bigint NOT NULL REFERENCES cowrie_botnet_peers(id) ON DELETE CASCADE,
  command_id bigint NOT NULL,
  PRIMARY KEY (peer_id, command_id)
);

CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_cowrie_peer_commands_command
  ON cowrie_peer_commands (command_id);

-- ---------------------------------------------------------------------------
-- 3. The launches themselves
-- ---------------------------------------------------------------------------
-- 46 of 163 launches pass no addresses at all and fall back to the binary's
-- embedded list. Those are data, not parse failures: the ratio of empty to
-- populated says how often the operator ships a fresh bootstrap set, and
-- recording only the populated ones would quietly overstate it.

CREATE TABLE IF NOT EXISTS cowrie_peer_lists (
  command_id  bigint PRIMARY KEY,
  peer_count  integer NOT NULL,
  first_seen  timestamptz NOT NULL,
  last_seen   timestamptz NOT NULL
);

-- ---------------------------------------------------------------------------
-- 4. Staging for the backfill
-- ---------------------------------------------------------------------------
CREATE UNLOGGED TABLE IF NOT EXISTS cowrie_peers_stage (
  peer_ip           inet NOT NULL,
  first_seen        timestamptz NOT NULL,
  last_seen         timestamptz NOT NULL,
  country_iso       text,
  asn               integer,
  org               text,
  city              text,
  source_command_id bigint NOT NULL
);

-- ---------------------------------------------------------------------------
-- 5. Catalog-only, as usual
-- ---------------------------------------------------------------------------
-- Nothing above populates anything. Migration 013's first version wrote 1.6M
-- rows inline, filled the volume and crashed PostgreSQL; since then a
-- migration changes the shape of the database and a backfill changes its
-- contents, because only the backfill can be paced, resumed, and made to
-- refuse to start when the disk is short.
--
-- Run db/backfill/015_botnet_peers.sh next.
